version: '3.8'
services:
  richmond-paper-supply-website:
    container_name: richmond-paper-supply-cdn
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - reverse-proxy
    pull_policy: build
    env_file: 
      - stack.env
networks:
  reverse-proxy:
    external: true
